In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/PhiUSIIL_Phishing_URL_Dataset.csv")

In [3]:
df.shape

(235795, 56)

In [4]:
df.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 56 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   FILENAME                    235795 non-null  str
 1   URL                         235795 non-null  str
 2   URLLength                   235795 non-null  int64
 3   Domain                      235795 non-null  str
 4   DomainLength                235795 non-null  int64
 5   IsDomainIP                  235795 non-null  int64
 6   TLD                         235795 non-null  str
 7   URLSimilarityIndex          235795 non-null  float64
 8   CharContinuationRate        235795 non-null  float64
 9   TLDLegitimateProb           235795 non-null  float64
 10  URLCharProb                 235795 non-null  float64
 11  TLDLength                   235795 non-null  int64
 12  NoOfSubDomain               235795 non-null  int64
 13  HasObfuscation              235795 non-null  int64
 14  NoOfObfuscatedChar          235795 non-null  int64
 15  ObfuscationRatio            235795 non-null  float64
 16  NoOfLettersInURL            235795 non-null  int64
 17  LetterRatioInURL            235795 non-null  float64
 18  NoOfDegitsInURL             235795 non-null  int64
 19  DegitRatioInURL             235795 non-null  float64
 20  NoOfEqualsInURL             235795 non-null  int64
 21  NoOfQMarkInURL              235795 non-null  int64
 22  NoOfAmpersandInURL          235795 non-null  int64
 23  NoOfOtherSpecialCharsInURL  235795 non-null  int64
 24  SpacialCharRatioInURL       235795 non-null  float64
 25  IsHTTPS                     235795 non-null  int64
 26  LineOfCode                  235795 non-null  int64
 27  LargestLineLength           235795 non-null  int64
 28  HasTitle                    235795 non-null  int64
 29  Title                       235795 non-null  str
 30  DomainTitleMatchScore       235795 non-null  float64
 31  URLTitleMatchScore          235795 non-null  float64
 32  HasFavicon                  235795 non-null  int64
 33  Robots                      235795 non-null  int64
 34  IsResponsive                235795 non-null  int64
 35  NoOfURLRedirect             235795 non-null  int64
 36  NoOfSelfRedirect            235795 non-null  int64
 37  HasDescription              235795 non-null  int64
 38  NoOfPopup                   235795 non-null  int64
 39  NoOfiFrame                  235795 non-null  int64
 40  HasExternalFormSubmit       235795 non-null  int64
 41  HasSocialNet                235795 non-null  int64
 42  HasSubmitButton             235795 non-null  int64
 43  HasHiddenFields             235795 non-null  int64
 44  HasPasswordField            235795 non-null  int64
 45  Bank                        235795 non-null  int64
 46  Pay                         235795 non-null  int64
 47  Crypto                      235795 non-null  int64
 48  HasCopyrightInfo            235795 non-null  int64
 49  NoOfImage                   235795 non-null  int64
 50  NoOfCSS                     235795 non-null  int64
 51  NoOfJS                      235795 non-null  int64
 52  NoOfSelfRef                 235795 non-null  int64
 53  NoOfEmptyRef                235795 non-null  int64
 54  NoOfExternalRef             235795 non-null  int64
 55  label                       235795 non-null  int64
dtypes: float64(10), int64(41), str(5)
memory usage: 100.7 MB

In [6]:
df.describe()

,URLLength,DomainLength,IsDomainIP,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,HasObfuscation,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
count,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,...,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000
mean,34.573095,21.470396,0.002706,78.430778,0.845508,0.260423,0.055747,2.764456,1.164758,0.002057,...,0.237007,0.023474,0.486775,26.075689,6.333111,10.522305,65.071113,2.377629,49.262516,0.571895
std,41.314153,9.150793,0.051946,28.976055,0.216632,0.251628,0.010587,0.599739,0.600969,0.045306,...,0.425247,0.151403,0.499826,79.411815,74.866296,22.312192,176.687539,17.641097,161.027430,0.494805
min,13.000000,4.000000,0.000000,0.155574,0.000000,0.000000,0.001083,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,23.000000,16.000000,0.000000,57.024793,0.680000,0.005977,0.050747,2.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,27.000000,20.000000,0.000000,100.000000,1.000000,0.079963,0.057970,3.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,8.000000,2.000000,6.000000,12.000000,0.000000,10.000000,1.000000
75%,34.000000,24.000000,0.000000,100.000000,1.000000,0.522907,0.062875,3.000000,1.000000,0.000000,...,0.000000,0.000000,1.000000,29.000000,8.000000,15.000000,88.000000,1.000000,57.000000,1.000000
max,6097.000000,110.000000,1.000000,100.000000,1.000000,0.522907,0.090824,13.000000,10.000000,1.000000,...,1.000000,1.000000,1.000000,8956.000000,35820.000000,6957.000000,27397.000000,4887.000000,27516.000000,1.000000

In [7]:
# Check for missing values
df.isna().sum().sort_values(ascending=False)

FILENAME                      0
URL                           0
DomainTitleMatchScore         0
URLTitleMatchScore            0
HasFavicon                    0
Robots                        0
IsResponsive                  0
NoOfURLRedirect               0
NoOfSelfRedirect              0
HasDescription                0
NoOfPopup                     0
NoOfiFrame                    0
HasExternalFormSubmit         0
HasSocialNet                  0
HasSubmitButton               0
HasHiddenFields               0
HasPasswordField              0
Bank                          0
Pay                           0
Crypto                        0
HasCopyrightInfo              0
NoOfImage                     0
NoOfCSS                       0
NoOfJS                        0
NoOfSelfRef                   0
NoOfEmptyRef                  0
NoOfExternalRef               0
Title                         0
HasTitle                      0
LargestLineLength             0
HasObfuscation                0
URLLength                     0
Domain                        0
DomainLength                  0
IsDomainIP                    0
TLD                           0
URLSimilarityIndex            0
CharContinuationRate          0
TLDLegitimateProb             0
URLCharProb                   0
TLDLength                     0
NoOfSubDomain                 0
NoOfObfuscatedChar            0
LineOfCode                    0
ObfuscationRatio              0
NoOfLettersInURL              0
LetterRatioInURL              0
NoOfDegitsInURL               0
DegitRatioInURL               0
NoOfEqualsInURL               0
NoOfQMarkInURL                0
NoOfAmpersandInURL            0
NoOfOtherSpecialCharsInURL    0
SpacialCharRatioInURL         0
IsHTTPS                       0
label                         0
dtype: int64

In [8]:
# Check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [ ]:
# Check target class distribution to make sure it is balanced
df["label"].value_counts()

label
1    134850
0    100945
Name: count, dtype: int64

In [11]:
# Identify string columns
df.select_dtypes(include="object").columns.tolist()

/var/folders/km/kgtp2fsd5w9c6td4r6ss58th0000gn/T/ipykernel_19791/3649239208.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns.tolist()

['FILENAME', 'URL', 'Domain', 'TLD', 'Title']

In [12]:
# Check number of unique values in string columns
df[["FILENAME", "URL", "Domain", "TLD", "Title"]].nunique()

FILENAME    235795
URL         235370
Domain      220086
TLD            695
Title       197874
dtype: int64

In [13]:
# Inspect numeric ranges
df.select_dtypes(include="number").describe().T[
    ["min", "max", "mean", "std"]
]

,min,max,mean,std
URLLength,13.000000,6.097000e+03,34.573095,41.314153
DomainLength,4.000000,1.100000e+02,21.470396,9.150793
IsDomainIP,0.000000,1.000000e+00,0.002706,0.051946
URLSimilarityIndex,0.155574,1.000000e+02,78.430778,28.976055
CharContinuationRate,0.000000,1.000000e+00,0.845508,0.216632
TLDLegitimateProb,0.000000,5.229071e-01,0.260423,0.251628
URLCharProb,0.001083,9.082366e-02,0.055747,0.010587
TLDLength,2.000000,1.300000e+01,2.764456,0.599739
NoOfSubDomain,0.000000,1.000000e+01,1.164758,0.600969
HasObfuscation,0.000000,1.000000e+00,0.002057,0.045306
NoOfObfuscatedChar,0.000000,4.470000e+02,0.024861,1.876249
ObfuscationRatio,0.000000,3.480000e-01,0.000138,0.003817
NoOfLettersInURL,0.000000,5.191000e+03,19.428919,29.090330
LetterRatioInURL,0.000000,9.260000e-01,0.515946,0.123315
NoOfDegitsInURL,0.000000,2.011000e+03,1.881011,11.886695
DegitRatioInURL,0.000000,6.840000e-01,0.028616,0.070897
NoOfEqualsInURL,0.000000,1.760000e+02,0.062241,0.934704
NoOfQMarkInURL,0.000000,4.000000e+00,0.029403,0.193505
NoOfAmpersandInURL,0.000000,1.490000e+02,0.025056,0.836448
NoOfOtherSpecialCharsInURL,0.000000,4.990000e+02,2.340198,3.527603
SpacialCharRatioInURL,0.000000,3.970000e-01,0.063309,0.032393
IsHTTPS,0.000000,1.000000e+00,0.782625,0.412461
LineOfCode,2.000000,4.426660e+05,1141.900443,3419.950513
LargestLineLength,22.000000,1.397573e+07,12789.532624,152201.099228
HasTitle,0.000000,1.000000e+00,0.861261,0.345675
DomainTitleMatchScore,0.000000,1.000000e+02,50.131427,49.676981
URLTitleMatchScore,0.000000,1.000000e+02,52.122098,49.600564
HasFavicon,0.000000,1.000000e+00,0.361768,0.480513
Robots,0.000000,1.000000e+00,0.266541,0.442151
IsResponsive,0.000000,1.000000e+00,0.624513,0.484249
NoOfURLRedirect,0.000000,1.000000e+00,0.133438,0.340048
NoOfSelfRedirect,0.000000,1.000000e+00,0.040107,0.196210
HasDescription,0.000000,1.000000e+00,0.440183,0.496410
NoOfPopup,0.000000,6.020000e+02,0.221765,3.870540
NoOfiFrame,0.000000,1.602000e+03,1.588638,5.762561
HasExternalFormSubmit,0.000000,1.000000e+00,0.043987,0.205067
HasSocialNet,0.000000,1.000000e+00,0.456570,0.498111
HasSubmitButton,0.000000,1.000000e+00,0.414301,0.492602
HasHiddenFields,0.000000,1.000000e+00,0.377799,0.484838
HasPasswordField,0.000000,1.000000e+00,0.102263,0.302994
Bank,0.000000,1.000000e+00,0.127089,0.333074
Pay,0.000000,1.000000e+00,0.237007,0.425247
Crypto,0.000000,1.000000e+00,0.023474,0.151403
HasCopyrightInfo,0.000000,1.000000e+00,0.486775,0.499826
NoOfImage,0.000000,8.956000e+03,26.075689,79.411815
NoOfCSS,0.000000,3.582000e+04,6.333111,74.866296
NoOfJS,0.000000,6.957000e+03,10.522305,22.312192
NoOfSelfRef,0.000000,2.739700e+04,65.071113,176.687539
NoOfEmptyRef,0.000000,4.887000e+03,2.377629,17.641097
NoOfExternalRef,0.000000,2.751600e+04,49.262516,161.027430
label,0.000000,1.000000e+00,0.571895,0.494805

In [14]:
# Check for columns with only one unique value
constant_columns = [col for col in df.columns if df[col].nunique() == 1]

constant_columns

[]

In [15]:
# Remove the unique identifier column
df = df.drop(columns=["FILENAME"])

In [16]:
df.shape

(235795, 55)

In [17]:
# Reverse our target variable so 0 = Legitimate, 1 = Phishing
df["label"] = 1 - df["label"]

In [18]:
df["label"].value_counts()

label
0    134850
1    100945
Name: count, dtype: int64

In [19]:
# Final validation
print("Shape:", df.shape)
print("Missing values:", df.isna().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("\nTarget distribution:")
print(df["label"].value_counts())

Shape: (235795, 55)
Missing values: 0
Duplicate rows: 0

Target distribution:
label
0    134850
1    100945
Name: count, dtype: int64

In [20]:
# Save our cleaned dataset
df.to_csv("../data/cleaned/phishing_cleaned.csv", index=False)